Local plugin support/documentation
megalinter/megalinter pull request #1508
Opened 2022-06-02 21:29 UTC by jackheuberger

Fixes #1507 

## Proposed Changes

1. Support for local plugin descriptor files under a custom "file://" header under the PLUGINS section of `.mega-linter.yml`
2. Documentation in the plugin section for the new schema

## Readiness Checklist

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2022-06-02 21:41 UTC, nvuillam requested changes
Great ! :)
Please could you add:
- a test class checking use of file plugin (if possible)
- Update README.md, because plugins.md if automatically generated from it :)
Thank a lot !

2022-06-02 22:45 UTC, jackheuberger commented
I think I changed everything correctly. Let me know if there's anything else!

2022-06-02 22:46 UTC, jackheuberger reviewed
Made the change in README, added a test in plugins_test.py

2022-06-03 06:30 UTC, nvuillam commented
Thanks 
Please can you also merge main into your branch then merge conflicts ? ( those 3 files are automatically generated so they way you merge them is not important ^^ )

2022-06-03 14:09 UTC, jackheuberger commented
Ok I think I fixed everything. Lmk if I messed something up somewhere but I think I did it correctly

2022-06-09 16:55 UTC, jackheuberger commented on megalinter/tests/test_megalinter/plugins_test.py
> +                + "main"
I hard-coded main in this instance as {ML_REPO} wasn't successfully pointing to my fork

2022-06-09 19:19 UTC, Kurt-von-Laven requested changes

2022-06-09 19:19 UTC, Kurt-von-Laven commented on .automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
> +    - RUN npm install jsonlint -g && echo "This is my test MegaLinter plugin !"
This is a minor pre-existing issue, but there shouldn't be a space before the exclamation point.

2022-06-09 19:30 UTC, jackheuberger commented on megalinter/tests/test_megalinter/plugins_test.py
> +                + "main"
Sounds good. I wrote a little blurb as to why the change was made with a note to maybe change in the future.

2022-06-12 09:23 UTC, nvuillam approved these changes
Thanks for your contribution :)

2022-06-12 09:24 UTC, merged